PRAGMA foreign_keys = ON;

CREATE TABLE users(
    name VARCHAR(64) PRIMARY KEY NOT NULL UNIQUE,
    balance INTEGER NOT NULL
    -- picture VARCHAR(128) NOT NULL
);

CREATE TABLE transactions(
  transactionid INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  amount INTEGER NOT NULL,
  date DATE NOT NULL,
  user VARCHAR,
  FOREIGN KEY(user) REFERENCES users(name) ON DELETE CASCADE
);